id = "cynosure-light-theme"
name = "Cynosure Light Theme"
version = "0.1.0"
schema_version = 1
authors = ["Storm Maxwell"]
description = "Cyberpunk 2077, Phantom Liberty inspired theme"
repository = "https://github.com/SM2507/cynosure-light-theme.git"

themes = ["themes/cynosure-light-theme.json"]
